version: "3"

services:
  web:
    build: ./app
    container_name: web
    volumes:
      - ./app:/src/app
    depends_on:
      - db

  interface:
    build: ./interface
    container_name: interface

  db:
    image: postgres
    container_name: db
    volumes:
      - db_data:/var/lib/postgresql/data/

volumes:
  db_data:
