version: "3"

services:
  web:
    build: ./app
    image: diana-backend-web
    container_name: web
    volumes:
      - ./app:/src/app
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: db
    volumes:
      - db_data:/var/lib/postgresql/data/

volumes:
  db_data:
