# Generated by Django 3.1.5 on 2021-01-13 11:20

import core.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('note', models.TextField()),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('priority', models.IntegerField(choices=[(0, 'P0'), (1, 'P1'), (2, 'P2'), (3, 'P3')], default=0, validators=[core.validators.BothIncludedRangeValidator(0, 3)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('done', models.BooleanField(default=False)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='core.task')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['user'], name='core_task_user_id_d25a04_idx'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(check=models.Q(('priority__gte', 0), ('priority__lte', 3)), name='valid_priority'),
        ),
    ]
