# Generated by Django 3.1.5 on 2021-01-15 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='reminder',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
