# Generated by Django 3.1.5 on 2021-01-18 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_task_reminder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
