# Generated by Django 3.1.5 on 2021-01-19 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210118_1112'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TasksTags',
            new_name='TaskTag',
        ),
        migrations.RemoveIndex(
            model_name='tasktag',
            name='core_taskst_task_id_f791a7_idx',
        ),
        migrations.RemoveIndex(
            model_name='tasktag',
            name='core_taskst_tag_id_3c6f17_idx',
        ),
        migrations.AddIndex(
            model_name='tasktag',
            index=models.Index(fields=['task'], name='core_taskta_task_id_75177e_idx'),
        ),
        migrations.AddIndex(
            model_name='tasktag',
            index=models.Index(fields=['tag'], name='core_taskta_tag_id_3ea7d4_idx'),
        ),
    ]
