# Generated by Django 3.1.5 on 2021-01-20 07:43

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210120_0651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, validators=[core.validators.FutureDateTimeValidator()]),
        ),
        migrations.AlterField(
            model_name='task',
            name='reminder',
            field=models.DateTimeField(blank=True, null=True, validators=[core.validators.FutureDateTimeValidator()]),
        ),
    ]
